---
title: "STT843: Multivariate Data Analysis"
subtitle: "Course Website - Spring 2026"
---

::: lead
Welcome to the course website for **STT843** 

This course provides an introduction to the statistical analysis of multivariate data, focusing on both theoretical foundations and practical applications in R.
:::

------------------------------------------------------------------------

## 📋 Course Information

-   🎓 **Instructor:** [Dr. Guanqun Cao]{style="color: #18453B; font-family: 'Arial Black', sans-serif;"}
-   🎓 **TA:**  Mr. Andrews Boahen (boahenan\@msu.edu)
-   ⏰ **Office Hours:** [Monday, 10am – 11am]{style="color: #007bff;"} \| C426 Wells Hall
-   📄 **Syllabus:** [click here 🔗](lectures/syllabus.pdf)  

## 🗓️ Weekly Schedule

::: callout-note
## Important Note

Lecture slides are updated every Sunday evening. Please ensure you have the latest version before Monday's class.
:::

| Week | Topic | Slides (PDF) | Labs (Rmd/Qmd) | Assignment |
|:-------------:|:--------------|:-------------:|:-------------:|:-------------:|
| 1 | [Introduction]{style="color: blue; font-weight: bold;"} | [Lec 1.1 🔗](lectures/lec01-intro.pdf)<br>[Lec 1.2 🔗](lectures/lec02-matrix.pdf) | [💻 Lab 1a](labs/lab01a.Rmd)<br>[💻 Lab 1b](labs/lab01b.Rmd) | -- |
| 2 | [Random Vectors and Matrices]{style="color: green; font-weight: bold;"} | [Lec 2.1 🔗](lectures/lec02_2.pdf)<br> [Lec 2.1* 🔗](lectures/matrices.pdf)<br> | [💻 Lab 2a](labs/lab02.Rmd)<br>  | [HW1 solution](lectures/HM1_sol.pdf){style="color: red;"} |
| 3 | [Multivariate Normal Distribution I]{style="color: blue; font-weight: bold;"} | [Lec 3.1 🔗](lectures/lec03a.pdf)<br>  [Lec 3.2 🔗](lectures/lec03b.pdf)<br> [Lec 3.1* 🔗](lectures/MVN.pdf)<br> | [💻 Lab 3a](labs/lab03a.Rmd)<br>[💻 Lab 3b](labs/lab03b.Rmd)  | [Quiz 1]{style="color: purple;"} |
| 4 | [Multivariate Normal Distribution II]{style="color: green; font-weight: bold;"} | [Lec 4.1 🔗](lectures/lec03c.pdf)<br>[Lec 4.2 🔗](lectures/lec03d.pdf) | [💻 Lab 3c](labs/lab03c.Rmd)<br>[💻 Lab 3d](labs/lab03d.Rmd)  | [HW2 solution](lectures/HW2_Sol.pdf){style="color: red;"} |
| 5 | [Mean Vector]{style="color: blue; font-weight: bold;"} | [Lec 5.1 🔗](lectures/lec04a.pdf)<br>[Lec 5.2 🔗](lectures/lec04b.pdf) | [💻 Lab 5a](labs/lab04a.Rmd)<br>[💻 Lab 5b](labs/lab04b.Rmd)  | -- |
| 6 | [Variance]{style="color: green; font-weight: bold;"} | [Lec 6.1 🔗](lectures/lec05a.pdf)<br>  | [💻 Lab 6a](labs/lab05a.Rmd)<br> |  [HW3/quiz2]{style="color: red;"}  |
| 7 | [Multivariate Linear Regression]{style="color: blue; font-weight: bold;"} | [Lec 7.1 🔗](lectures/lec06a.pdf)<br> [Lec 7.2 🔗](lectures/lec06b.pdf) | [💻 Lab 7a](labs/lab06a.Rmd)<br>[💻 Lab 7b](labs/lab06b.Rmd) | --|
|8|[Exam 1]{style="color: green; font-weight: bold;"}| | | --|
|9|[Project Preparation]{style="color: blue; font-weight: bold;"}| [project 🔗](lectures/final.pdf)<br>| | [proposal]{style="color: red;"} |
| 10 | [Principal Component Analysis]{style="color: green; font-weight: bold;"} | [Lec 8.1 🔗](lectures/lec07a.pdf)<br> [Lec 8.2 🔗](lectures/lec07b.pdf) | [💻 Lab 8a](labs/lab07a.Rmd)<br>[💻 Lab 8b](labs/lab07b.Rmd) | --|


## 🛠️ Software Requirements

We will be using **R** and **RStudio** for all computations. Please ensure you have the following installed:

[1.]{.underline} \[R (version 4.3+)\](<https://cran.r-project.org/>)

[2.]{.underline} \[RStudio Desktop\](<https://posit.co/download/rstudio-desktop>/)

[3.]{.underline} \[Quarto CLI\](<https://quarto.org/docs/get-started/>)
